"""001_baseline

Revision ID: 001
Revises: 
Create Date: 2026-02-24 12:34:19.369069
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('cache_key', sa.String(length=256), nullable=False),
    sa.Column('cache_type', sa.String(length=20), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('series_status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_cache_cache_type'), ['cache_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_cache_expires_at'), ['expires_at'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_profiles',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('composition_type', sa.String(length=30), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('session_zero_states',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('last_activity', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('wiki_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.String(length=100), nullable=False),
    sa.Column('page_title', sa.String(length=500), nullable=False),
    sa.Column('page_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('source_wiki', sa.String(length=200), nullable=True),
    sa.Column('scraped_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'page_title', name='uq_wiki_profile_title')
    )
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.create_index('idx_wiki_profile_type', ['profile_id', 'page_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_wiki_pages_profile_id'), ['profile_id'], unique=False)

    op.create_table('campaign_bible',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('planning_data', sa.JSON(), nullable=True),
    sa.Column('bible_version', sa.Integer(), nullable=True),
    sa.Column('last_updated_turn', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('xp_current', sa.Integer(), nullable=True),
    sa.Column('xp_to_next_level', sa.Integer(), nullable=True),
    sa.Column('character_class', sa.String(length=100), nullable=True),
    sa.Column('hp_current', sa.Integer(), nullable=True),
    sa.Column('hp_max', sa.Integer(), nullable=True),
    sa.Column('mp_current', sa.Integer(), nullable=True),
    sa.Column('mp_max', sa.Integer(), nullable=True),
    sa.Column('sp_current', sa.Integer(), nullable=True),
    sa.Column('sp_max', sa.Integer(), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.Column('power_tier', sa.String(length=10), nullable=True),
    sa.Column('abilities', sa.JSON(), nullable=True),
    sa.Column('inventory', sa.JSON(), nullable=True),
    sa.Column('op_enabled', sa.Boolean(), nullable=True),
    sa.Column('op_tension_source', sa.String(length=50), nullable=True),
    sa.Column('op_power_expression', sa.String(length=50), nullable=True),
    sa.Column('op_narrative_focus', sa.String(length=50), nullable=True),
    sa.Column('op_preset', sa.String(length=50), nullable=True),
    sa.Column('narrative_goals', sa.JSON(), nullable=True),
    sa.Column('calibration_score', sa.Float(), nullable=True),
    sa.Column('story_flags', sa.JSON(), nullable=True),
    sa.Column('concept', sa.Text(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('backstory', sa.Text(), nullable=True),
    sa.Column('appearance', sa.JSON(), nullable=True),
    sa.Column('visual_tags', sa.JSON(), nullable=True),
    sa.Column('model_sheet_url', sa.String(length=500), nullable=True),
    sa.Column('portrait_url', sa.String(length=500), nullable=True),
    sa.Column('personality_traits', sa.JSON(), nullable=True),
    sa.Column('values', sa.JSON(), nullable=True),
    sa.Column('fears', sa.JSON(), nullable=True),
    sa.Column('quirks', sa.JSON(), nullable=True),
    sa.Column('short_term_goal', sa.Text(), nullable=True),
    sa.Column('long_term_goal', sa.Text(), nullable=True),
    sa.Column('faction', sa.String(length=100), nullable=True),
    sa.Column('faction_reputations', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consequences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('turn', sa.Integer(), nullable=False),
    sa.Column('source_action', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('expires_turn', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('alignment', sa.String(length=50), nullable=True),
    sa.Column('power_level', sa.String(length=50), nullable=True),
    sa.Column('influence_score', sa.Integer(), nullable=True),
    sa.Column('relationships', sa.JSON(), nullable=True),
    sa.Column('pc_is_member', sa.Boolean(), nullable=True),
    sa.Column('pc_rank', sa.String(length=100), nullable=True),
    sa.Column('pc_reputation', sa.Integer(), nullable=True),
    sa.Column('pc_controls', sa.Boolean(), nullable=True),
    sa.Column('subordinates', sa.JSON(), nullable=True),
    sa.Column('faction_goals', sa.JSON(), nullable=True),
    sa.Column('secrets', sa.JSON(), nullable=True),
    sa.Column('current_events', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foreshadowing_seeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('seed_id', sa.String(length=100), nullable=False),
    sa.Column('seed_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('planted_narrative', sa.Text(), nullable=True),
    sa.Column('expected_payoff', sa.Text(), nullable=True),
    sa.Column('planted_turn', sa.Integer(), nullable=False),
    sa.Column('planted_session', sa.Integer(), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=True),
    sa.Column('last_mentioned_turn', sa.Integer(), nullable=True),
    sa.Column('min_turns_to_payoff', sa.Integer(), nullable=True),
    sa.Column('max_turns_to_payoff', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Float(), nullable=True),
    sa.Column('resolved_turn', sa.Integer(), nullable=True),
    sa.Column('resolution_narrative', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('related_npcs', sa.JSON(), nullable=True),
    sa.Column('related_locations', sa.JSON(), nullable=True),
    sa.Column('depends_on', sa.JSON(), nullable=True),
    sa.Column('triggers', sa.JSON(), nullable=True),
    sa.Column('conflicts_with', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seed_id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=True),
    sa.Column('location_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('visual_tags', sa.JSON(), nullable=True),
    sa.Column('atmosphere', sa.String(length=100), nullable=True),
    sa.Column('lighting', sa.String(length=100), nullable=True),
    sa.Column('scale', sa.String(length=50), nullable=True),
    sa.Column('parent_location', sa.String(length=255), nullable=True),
    sa.Column('connected_locations', sa.JSON(), nullable=True),
    sa.Column('current_state', sa.String(length=100), nullable=True),
    sa.Column('state_history', sa.JSON(), nullable=True),
    sa.Column('discovered_turn', sa.Integer(), nullable=True),
    sa.Column('times_visited', sa.Integer(), nullable=True),
    sa.Column('last_visited_turn', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('notable_events', sa.JSON(), nullable=True),
    sa.Column('known_npcs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('power_tier', sa.String(length=10), nullable=True),
    sa.Column('faction', sa.String(length=100), nullable=True),
    sa.Column('affinity', sa.Integer(), nullable=True),
    sa.Column('disposition', sa.Integer(), nullable=True),
    sa.Column('relationship_notes', sa.Text(), nullable=True),
    sa.Column('knowledge_topics', sa.JSON(), nullable=True),
    sa.Column('knowledge_boundaries', sa.JSON(), nullable=True),
    sa.Column('personality', sa.Text(), nullable=True),
    sa.Column('goals', sa.JSON(), nullable=True),
    sa.Column('secrets', sa.JSON(), nullable=True),
    sa.Column('ensemble_archetype', sa.String(length=50), nullable=True),
    sa.Column('growth_stage', sa.String(length=50), nullable=True),
    sa.Column('narrative_role', sa.String(length=50), nullable=True),
    sa.Column('intelligence_stage', sa.String(length=50), nullable=True),
    sa.Column('emotional_milestones', sa.JSON(), nullable=True),
    sa.Column('scene_count', sa.Integer(), nullable=True),
    sa.Column('last_appeared', sa.Integer(), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('appearance', sa.JSON(), nullable=True),
    sa.Column('visual_tags', sa.JSON(), nullable=True),
    sa.Column('model_sheet_url', sa.String(length=500), nullable=True),
    sa.Column('portrait_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('quest_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('objectives', sa.JSON(), nullable=True),
    sa.Column('created_turn', sa.Integer(), nullable=True),
    sa.Column('completed_turn', sa.Integer(), nullable=True),
    sa.Column('related_npcs', sa.JSON(), nullable=True),
    sa.Column('related_locations', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('turn_count', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('world_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('time_of_day', sa.String(length=50), nullable=True),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('arc_name', sa.String(length=255), nullable=True),
    sa.Column('arc_phase', sa.String(length=50), nullable=True),
    sa.Column('tension_level', sa.Float(), nullable=True),
    sa.Column('turns_in_phase', sa.Integer(), nullable=True),
    sa.Column('timeline_mode', sa.String(length=50), nullable=True),
    sa.Column('canon_cast_mode', sa.String(length=50), nullable=True),
    sa.Column('event_fidelity', sa.String(length=50), nullable=True),
    sa.Column('foreshadowing', sa.JSON(), nullable=True),
    sa.Column('pinned_messages', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('cutscene_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('motion_prompt', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('player_input', sa.Text(), nullable=False),
    sa.Column('intent', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.JSON(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('state_changes', sa.JSON(), nullable=True),
    sa.Column('portrait_map', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('prompt_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('prompt_name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turns')
    op.drop_table('media_assets')
    op.drop_table('world_state')
    op.drop_table('sessions')
    op.drop_table('quests')
    op.drop_table('overrides')
    op.drop_table('npcs')
    op.drop_table('locations')
    op.drop_table('foreshadowing_seeds')
    op.drop_table('factions')
    op.drop_table('consequences')
    op.drop_table('characters')
    op.drop_table('campaign_bible')
    with op.batch_alter_table('wiki_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wiki_pages_profile_id'))
        batch_op.drop_index('idx_wiki_profile_type')

    op.drop_table('wiki_pages')
    op.drop_table('session_zero_states')
    op.drop_table('session_profiles')
    op.drop_table('campaigns')
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cache_expires_at'))
        batch_op.drop_index(batch_op.f('ix_api_cache_cache_type'))

    op.drop_table('api_cache')
    # ### end Alembic commands ###
